using Countries.Domain.Entities;
using Countries.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace Countries.Infrastructure.Seeder
{
    internal class CountrySeeder(
        ApplicationDbContext _context) : ICountrySeeder
    {
        public async Task Seed()
        {
            if (!await _context.Database.CanConnectAsync())
            {
                throw new InvalidOperationException(
                    "Could not connect to the database to seed the data.");
            }

            var hasCountries = await _context.Countries
                .IgnoreQueryFilters()
                .AnyAsync();

            if (hasCountries)
            {
                return;
            }

            var countries = GetCountries();

            await _context.Countries.AddRangeAsync(countries);

            await _context.SaveChangesAsync();
        }

        // These Countries and cities are generated by AI
        private static IEnumerable<Country> GetCountries()
        {
            return new List<Country>
        {
            CreateCountry("Egypt", "EG",
                "Cairo", "Alexandria", "Giza", "Luxor", "Aswan",
                "Port Said", "Suez", "Ismailia", "Mansoura", "Tanta",
                "Zagazig", "Damanhur", "Minya", "Sohag", "Assiut"),

            CreateCountry("Saudi Arabia", "SA",
                "Riyadh", "Jeddah", "Dammam", "Mecca",
                "Medina", "Taif", "Tabuk", "Abha"),

            CreateCountry("United Arab Emirates", "AE",
                "Abu Dhabi", "Dubai", "Sharjah", "Ajman",
                "Al Ain", "Fujairah", "Ras Al Khaimah", "Umm Al Quwain"),

            CreateCountry("United Kingdom", "GB",
                "London", "Manchester", "Birmingham", "Liverpool",
                "Leeds", "Bristol", "Edinburgh", "Glasgow"),

            CreateCountry("Germany", "DE",
                "Berlin", "Munich", "Hamburg", "Frankfurt",
                "Cologne", "Stuttgart", "Dresden", "Leipzig"),

            CreateCountry("United States", "US",
                "New York", "Los Angeles", "Chicago", "Houston",
                "Phoenix", "Philadelphia", "San Diego", "Dallas"),

            CreateCountry("Canada", "CA",
                "Toronto", "Vancouver", "Montreal", "Ottawa",
                "Calgary", "Edmonton", "Winnipeg", "Quebec City"),

            CreateCountry("France", "FR",
                "Paris", "Lyon", "Marseille", "Toulouse",
                "Nice", "Nantes", "Strasbourg", "Bordeaux"),

            CreateCountry("Italy", "IT",
                "Rome", "Milan", "Naples", "Turin",
                "Florence", "Bologna", "Venice", "Palermo"),

            CreateCountry("Spain", "ES",
                "Madrid", "Barcelona", "Valencia", "Seville",
                "Zaragoza", "Malaga", "Murcia", "Bilbao"),

            CreateCountry("Netherlands", "NL",
                "Amsterdam", "Rotterdam", "The Hague", "Utrecht",
                "Eindhoven", "Groningen", "Leiden", "Delft"),

            CreateCountry("Switzerland", "CH",
                "Zurich", "Geneva", "Basel", "Bern",
                "Lausanne", "Lucerne", "Lugano", "Winterthur"),

            CreateCountry("Turkey", "TR",
                "Istanbul", "Ankara", "Izmir", "Bursa",
                "Antalya", "Konya", "Adana", "Gaziantep"),

            CreateCountry("India", "IN",
                "New Delhi", "Mumbai", "Bengaluru", "Chennai",
                "Hyderabad", "Kolkata", "Pune", "Jaipur"),

            CreateCountry("China", "CN",
                "Beijing", "Shanghai", "Guangzhou", "Shenzhen",
                "Chengdu", "Wuhan", "Hangzhou", "Nanjing"),

            CreateCountry("Japan", "JP",
                "Tokyo", "Osaka", "Kyoto", "Yokohama",
                "Nagoya", "Sapporo", "Kobe", "Fukuoka"),

            CreateCountry("Australia", "AU",
                "Sydney", "Melbourne", "Brisbane", "Perth",
                "Adelaide", "Canberra", "Hobart", "Darwin"),

            CreateCountry("Brazil", "BR",
                "Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador",
                "Fortaleza", "Recife", "Curitiba", "Manaus"),

            CreateCountry("Ireland", "IE"),

            CreateCountry("Iceland", "IS")
        };
        }

        // Creates a new Country object with the specified name, code, and city names.
        private static Country CreateCountry(string name, string code, params string[] cityNames)
        {
            return new Country
            {
                Name = name,
                Code = code,
                Cities = cityNames
                    .Select(cityName => new City
                    {
                        Name = cityName
                    }).ToList()
            };
        }

    }
}